# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: go-integration-tests

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.21.6' ]
        node-version: [ '16.20.2' ]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go ${{ matrix.go-version }}
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}
    
    - name: Display Go version
      run: go version

    - name: Install dependencies
      run: go get .
    
    - name: Install gotestfmt
      run: go install github.com/gotesttools/gotestfmt/v2/cmd/gotestfmt@latest
    
    - name: Install gocover-cobertura
      run: go install github.com/boumenot/gocover-cobertura@latest

    - name: Set up Node ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: https://registry.npmjs.org/

    - name: Install newman
      run: npm install -g newman

    - name: Run the API and Postman's tests
      run: | 
        go run ./main.go &
        sleep 10
        newman run "go-tests.postman_collection.json"